name: "markdown"

on:
  push:
    branches:
      - "master"
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  lint:
    name: markdown lint
    runs-on: ubuntu-latest
    container: tmknom/markdownlint:latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Lint markdown files
        run: '
          find . -type f \( -name "*.md" \) -print |
          while IFS="" read -r file;
          do /usr/bin/markdownlint -c .markdownlint.yaml "$file"; done;
        '
